services:
  - type: web
    name: cv-lea
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    envVars:
      - key: NODE_VERSION
        value: 18
